@AutoFix_HostAddress = http://localhost:5089

#if (EnableOpenAPI)
GET {{AutoFix_HostAddress}}/openapi/v1.json
Accept: application/json

###
#endif

GET {{AutoFix_HostAddress}}/weatherforecast/
Accept: application/json

###
